In [1]:
import pandas as pd
import sys
sys.path.append('../')
from src.utils.functions import read_dataframe

In [2]:
test_df = read_dataframe("./wine_data/train_wine_data.csv")
actual_df = pd.read_csv("./wine_data/train_wine_data.csv")

In [3]:
actual_df

,type,fixed_acidity,volatile_acidity,citric_acid,residual_sugar,chlorides,free_sulfur_dioxide,total_sulfur_dioxide,density,pH,sulphates,alcohol,quality
0,white,7.4,0.170,0.29,1.4,0.047,23.0,107.0,0.99390,3.52,0.65,10.4,6
1,white,5.3,0.310,0.38,10.5,0.031,53.0,140.0,0.99321,3.34,0.46,11.7,6
2,white,4.7,0.145,0.29,1.0,0.042,35.0,90.0,0.99080,3.76,0.49,11.3,6
3,white,6.9,0.260,0.29,4.2,0.043,33.0,114.0,0.99020,3.16,0.31,12.5,6
4,white,6.4,0.450,0.07,1.1,0.030,10.0,131.0,0.99050,2.97,0.28,10.8,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...
32480,white,5.0,0.255,0.22,2.7,0.043,46.0,153.0,0.99238,3.75,0.76,11.3,6
32481,white,6.6,0.360,0.52,11.3,0.046,8.0,110.0,0.99660,3.07,0.46,9.4,5
32482,white,6.3,0.200,0.24,1.7,0.052,36.0,135.0,0.99374,3.80,0.66,10.8,6
32483,white,6.2,0.200,0.33,5.4,0.028,21.0,75.0,0.99012,3.36,0.41,13.5,7
32484,white,8.1,0.280,0.46,15.4,0.059,32.0,177.0,1.00040,3.27,0.58,9.0,4

In [4]:
test_df

,type,fixed_acidity,volatile_acidity,citric_acid,residual_sugar,chlorides,free_sulfur_dioxide,total_sulfur_dioxide,density,pH,sulphates,alcohol,quality
0,1,7.4,0.170,0.29,1.4,0.047,23.0,107.0,0.99390,3.52,0.65,10.4,6
1,1,5.3,0.310,0.38,10.5,0.031,53.0,140.0,0.99321,3.34,0.46,11.7,6
2,1,4.7,0.145,0.29,1.0,0.042,35.0,90.0,0.99080,3.76,0.49,11.3,6
3,1,6.9,0.260,0.29,4.2,0.043,33.0,114.0,0.99020,3.16,0.31,12.5,6
4,1,6.4,0.450,0.07,1.1,0.030,10.0,131.0,0.99050,2.97,0.28,10.8,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...
32480,1,5.0,0.255,0.22,2.7,0.043,46.0,153.0,0.99238,3.75,0.76,11.3,6
32481,1,6.6,0.360,0.52,11.3,0.046,8.0,110.0,0.99660,3.07,0.46,9.4,5
32482,1,6.3,0.200,0.24,1.7,0.052,36.0,135.0,0.99374,3.80,0.66,10.8,6
32483,1,6.2,0.200,0.33,5.4,0.028,21.0,75.0,0.99012,3.36,0.41,13.5,7
32484,1,8.1,0.280,0.46,15.4,0.059,32.0,177.0,1.00040,3.27,0.58,9.0,4

In [6]:
print(len(test_df.columns))

13

In [17]:
import mlflow

runs = mlflow.search_runs()

# Convert DataFrame to list of Run objects
run_objs = runs[["run_id", "artifact_uri"]].to_dict(orient="records")  

# Access run by index 
run = mlflow.get_run(run_objs[1]["run_id"])

print(run.data.tags)

{'developer': 'Sven', 'mlflow.log-model.history': '[{"run_id": "8de9ef331ed84ddf95c139dd26cd6cd4", "artifact_path": "model", "utc_time_created": "2024-02-01 16:01:35.091105", "flavors": {"python_function": {"model_path": "model.pkl", "predict_fn": "predict", "loader_module": "mlflow.sklearn", "python_version": "3.9.18", "env": {"conda": "conda.yaml", "virtualenv": "python_env.yaml"}}, "sklearn": {"pickled_model": "model.pkl", "sklearn_version": "1.2.2", "serialization_format": "cloudpickle", "code": null}}, "model_uuid": "f73944ce5fed458daa8cb8f1bac4f723", "mlflow_version": "2.3.1"}]', 'mlflow.runName': 'exultant-sponge-831', 'mlflow.source.git.commit': '997731b0c6faa806c167437bc31c27b184f20e06', 'mlflow.source.name': 'testTraining.py', 'mlflow.source.type': 'LOCAL', 'mlflow.user': 'sven', 'model': 'ExtraTreesClassifier'}

In [18]:
print(run.data.tags['developer'])

Sven

In [14]:
run = mlflow.get_run(mlflow.active_run().info.run_id)
print(run)

AttributeError: 'NoneType' object has no attribute 'info'

In [15]:
with mlflow.start_run():
    run = mlflow.get_run(mlflow.active_run().info.run_id)
    print(run)

<Run: data=<RunData: metrics={}, params={}, tags={'mlflow.runName': 'melodic-cat-435',
 'mlflow.source.name': '/home/sven/anaconda3/envs/exp-tracking-env/lib/python3.9/site-packages/ipykernel_launcher.py',
 'mlflow.source.type': 'LOCAL',
 'mlflow.user': 'sven'}>, info=<RunInfo: artifact_uri='file:///mnt/c/Users/Dev/desktop/mlops_project/tests/mlruns/0/059b7a51f4fb4749a565323c6428f451/artifacts', end_time=None, experiment_id='0', lifecycle_stage='active', run_id='059b7a51f4fb4749a565323c6428f451', run_name='melodic-cat-435', run_uuid='059b7a51f4fb4749a565323c6428f451', start_time=1706806441659, status='RUNNING', user_id='sven'>>

In [16]:
print(run.data.tags)

{'mlflow.runName': 'melodic-cat-435', 'mlflow.source.name': '/home/sven/anaconda3/envs/exp-tracking-env/lib/python3.9/site-packages/ipykernel_launcher.py', 'mlflow.source.type': 'LOCAL', 'mlflow.user': 'sven'}

In [19]:
my_df = pd.read_csv('/mnt/c/Users/Dev/desktop/mlops_project/tests/wine_data/test_wine_data.csv')
my_df

,type,fixed_acidity,volatile_acidity,citric_acid,residual_sugar,chlorides,free_sulfur_dioxide,total_sulfur_dioxide,density,pH,sulphates,alcohol,quality
0,white,7.0,0.270,0.36,20.7,0.045,45.0,170.0,1.00100,3.00,0.45,8.8,6
1,white,6.3,0.300,0.34,1.6,0.049,14.0,132.0,0.99400,3.30,0.49,9.5,6
2,white,8.1,0.280,0.40,6.9,0.050,30.0,97.0,0.99510,3.26,0.44,10.1,6
3,white,7.2,0.230,0.32,8.5,0.058,47.0,186.0,0.99560,3.19,0.40,9.9,6
4,white,7.2,0.230,0.32,8.5,0.058,47.0,186.0,0.99560,3.19,0.40,9.9,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...
6492,red,6.2,0.600,0.08,2.0,0.090,32.0,44.0,0.99490,3.45,0.58,10.5,5
6493,red,5.9,0.550,0.10,2.2,0.062,39.0,51.0,0.99512,3.52,NaN,11.2,6
6494,red,6.3,0.510,0.13,2.3,0.076,29.0,40.0,0.99574,3.42,0.75,11.0,6
6495,red,5.9,0.645,0.12,2.0,0.075,32.0,44.0,0.99547,3.57,0.71,10.2,5
6496,red,6.0,0.310,0.47,3.6,0.067,18.0,42.0,0.99549,3.39,0.66,11.0,6